public class TriggerHandler {
    public static void InsertMethod(List<Product_Table__c> productTables){
/*        List<Product_Table__c> productTablesList = Database.query('SELECT Id FROM Warehouse__c');
        for (Product_Table__c pt : productTablesList ){
            //List<> whFit;
            for (Warehouse__c wh : whFit ){
                //List add
            }
            if(List.isEmpty){
				Warehouse__c newWhRec = new Warehouse__c;
				newWhRec.Name = ('Warehouse' + Product_Table.Added_Date__с + ' ' + Product_Table.Added_Date__с + Org_Configuration.Period_Term__с);
				newWhRec.Period_Start__c = Product_Table.Added_Date__с;
				newWhRec.Period_End__c = Product_Table.Added_Date__с + Org_Configuration.Period_Term__с;
			}
			else {
				pt.Warehouse = 	newWhRec[0].Id;
			}
       	 }
	//upsert List*/
	}
}